name: Release Containerimage

on:
  workflow_dispatch:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        name: checkout

      # build the container image and release it as a package in this repository
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: push-container-image
        with:
          image: auto-update-renovate
          registry: ghcr.io
          dockerfile: Containerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # if the branch is main, add the latest tag
          addLatest: ${{ github.ref == 'refs/heads/main' }}